name: Daily Airfare Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      

      - name: Run airfare monitor
        run: python src/main.py

      - name: Show directory structure (debug)
        run: ls -R .
